@startuml

left to right direction
:Cliente: -- (Meter Dinero)
:Cliente: -- (Pedir azucar)
:Cliente: -- (Pedir Producto)
:Cliente: -- (Cancelar)
(Pedir Producto) ..> (Devolver Dinero) : <<include>>
(Cancelar) ..> (Devolver Dinero) : <<include>>
@enduml