@startuml
left to right direction
:new Actor: -- (Idenficarse)
:new Actor: -- (Pagar)
:new Actor: -- (Elegir mensajero)
:new Actor: -- (Confirmar)
(Pagar) <|-- (Pagar con tarjeta)
(Pagar) <|-- (Pagar con transferencia)
(Idenficarse) <.. (Registrarse) : <<extend>>

@enduml